[package]
name = "rust-chat"
version = "0.2.1"
authors = ["Nikita Baksalyar <nikita.baksalyar@gmail.com>"]

[dependencies]
#mio-websocket = { git = "https://github.com/mypianoplayer/mio-websocket" }
mio-websocket = { path = "../mio-websocket" }
env_logger = "0.3"
mio = "0.5.0"
